#+LATEX_HEADER: \usepackage[round]{natbib} 
#+LaTeX_HEADER: \usepackage{geometry}
#+LaTeX_HEADER: \usepackage{helvet}
#+LaTeX_HEADER: \geometry{left=3.5cm, right=2.5cm, top=2.5cm, bottom=2.5cm}
#+LaTeX_HEADER: \linespread{1.25}
#+OPTIONS: toc:nil

* Agradecimientos

Agradezco a CONICYT Proyecto Fondecyt Regular N°1170292 por la financiación de esta investigación.

\newpage
* Resumen

Decisions are part of our daily lives, and it appears as if some kind of process
is evaluating second to second all of our options. In all of such situations a
big question arises, should I go for the well-known option or should I take my
chances a look for a new one?. This *exploration-exploitation dilemma* is also
present in both, foraging for resources and *semantic search*. As such, both
problems can be seen as decision-making processes where resources and semantic
contents locations are unknown, and somehow one must establish an efficient criterion
for searching in an efficient way. Certain search patterns, which are
ubiquitous across many taxa, seems to provide an optimal way for foraging
through a previously unknown environment. Given that both semantic search and
foraging share similarities, an evolutionary co-option of the mechanisms
controlling foraging for semantic search is discussed. Underlying strategies for
searching through patchy environments, neural implementations of
exploration-exploitation control and internal aspects of foraging are discussed
in hopes of providing an evolutionary framework for semantic search research.

\newpage
* Tabla de contenido
#+TOC: headlines 2 
\newpage
* Índices de ilustraciones

\newpage
* Introduction
** Semantic search
*** What it is
Semantic memories are memories about the meaning of things, this conceptual
knowlegde allows us to interact and recognize objects, plan the future and
remember the past citep:binderNeurobiologySemanticMemory2011. Given such pivotal
role, the way that we 'navigate' through such memories will determine the way we
interact with the world. The space in which the 'navigation' occurs has been
called semantic space, which corresponds to an abstraction where semantic
memories are placed in a multi-dimensional space and the conection between them
are defined by some vector assigning the relationship between each one in every
dimension citep:lundProducingHighdimensionalSemantic1996a. In humans, however,
that way that semantic memories organize into such space is not clear
citep:benedekHowSemanticMemory2017.  
*** Empirical evidence and space justificaction

Free recall tasks, which prompt the participant to recall as many objects
pertaining to a certain category in a limited amount of time, have observed a
'patchy' distribution of such memories citep:hillsOptimalForagingSemantic2009,
this patchy distribution refers to a signicantly faster retrieval time when the
participant are within a certain category (which is determined beforehand), more
than when they're not. The idea of a semantic space, with distances between contents, was
first developed by supervised semantic network modeling based on lexical
co-ocurrence citep:lundProducingHighdimensionalSemantic1996a, which found
correlations between the distances calculated by this model and human reaction
times.

The specific way this 'distance' exists in the brain is not known, however,
earlier studies lesion studies showed that specific neurological damage affect
specific semantic categories
citep:hillisCATEGORYSPECIFICNAMINGCOMPREHENSION1991, tempting that this
categories have some physical distance between them. Functional neuroimaging
data points in a similar direction, but is not clear wether the structure
represents actual semantic categories or some modality-specifc sub-divisions
citep:caramazzaOrganizationConceptualKnowledge2003,binderWhereSemanticSystem2009.
Network science studies have indicated that within category elements present
lower average shortest path length, higher clustering coefficient and lower
network modularity, implying that semantic contents are distributed in dense
clusters pertaining to each category and that access to items within a category
have efficient access between them compared to another category
citep:benedekHowSemanticMemory2017.
*** Observed patterns

Given a semantic space with a clustered-patchy distribution, the question of how
to efficiently retrieve such contenst arises. Recall tasks data points that
inter-retrieval intervals (IRI) when participants are producing items within a given
category are signicantly shorter that when they are not
citep:abbottRandomWalksSemantic2015a. IRI on this type of task have shown to be
following a Lévy probability density distribution with an exponent near 2 when
the retrievals are more efficient citep:rhodesHumanMemoryRetrieval2007a 

pattern describing such inter-retrieval intervals have been compared to that of
food-foraging citep:rhodesHumanMemoryRetrieval2007a, this suggest a notion of
distance between memory contents that has been observed when participants are
asked to represent in a 2D space such memories
citep:montezRoleSemanticClustering2015 
** Sequential decision making
*** What is the 'problem' present in semantic search (specific to retrieval tasks)
*** Brief intro to sequential decision making an its issue (da paso a exploration-exploitation)
** The exploration-exploitation dilemma in foraging and semantic search
*** Presentar el dilemma
*** Connect both through evidence
*** Connect both through logic
\newpage
* Models for a Heuristic
*** Define heuristics clearly
*** Put the question of what is the underlying heuristic
*** Argue how a model could represent a heuristic
*** Rule-based
*** Random walks
\newpage
* A case of co-option
*** Introduce the concept of co-option, emphasis on behavioral or search traits
*** From where semantic search is co-opted from ? introduce foraging
*** How this came to be
\newpage
* Neural implementations
*** Once a strategy/heuristic is identified, it is necesary to identify the structure underlying it
*** Base on exploration exploitation dilemma
\newpage
* State dependent foraging
\newpage
* Conclusions
\newpage
* References

bibliographystyle:apa
bibliography:references.bib









